# Generated by Django 5.1.6 on 2025-04-24 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chemistry', '0002_element_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('first_action', 'Первое действие'), ('first_element', 'Первый элемент'), ('first_quiz', 'Первая викторина'), ('three_correct_answers', 'Три правильных ответа подряд'), ('first_search', 'Первый поиск'), ('custom', 'Другое достижение')], default='custom', max_length=50, verbose_name='Тип достижения'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Эмодзи'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='fas fa-award', max_length=50, verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='UserFavoriteReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemistry.chemicalreaction', verbose_name='Реакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная реакция',
                'verbose_name_plural': 'Избранные реакции',
                'unique_together': {('user', 'reaction')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_reactions',
            field=models.ManyToManyField(related_name='favorited_by', through='accounts.UserFavoriteReaction', to='chemistry.chemicalreaction', verbose_name='Избранные реакции'),
        ),
    ]
