# Generated by Django 5.1.6 on 2025-04-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('symbol', models.CharField(max_length=3, verbose_name='Символ')),
                ('atomic_number', models.PositiveSmallIntegerField(unique=True, verbose_name='Атомный номер')),
                ('atomic_weight', models.FloatField(verbose_name='Атомная масса')),
                ('group', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Группа')),
                ('period', models.PositiveSmallIntegerField(verbose_name='Период')),
                ('image', models.ImageField(blank=True, null=True, upload_to='elements/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fun_facts', models.TextField(blank=True, verbose_name='Интересные факты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Химический элемент',
                'verbose_name_plural': 'Химические элементы',
                'ordering': ['atomic_number'],
            },
        ),
        migrations.CreateModel(
            name='ElementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#FFFFFF', help_text='#RRGGBB', max_length=7, verbose_name='Цвет (HEX)')),
            ],
            options={
                'verbose_name': 'Категория элемента',
                'verbose_name_plural': 'Категории элементов',
            },
        ),
        migrations.CreateModel(
            name='ChemicalReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('reaction_formula', models.CharField(max_length=255, verbose_name='Формула реакции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video', models.FileField(blank=True, null=True, upload_to='reaction_videos/', verbose_name='Видео реакции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reaction_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('products', models.ManyToManyField(related_name='reactions_as_product', to='chemistry.element', verbose_name='Продукты')),
                ('reactants', models.ManyToManyField(related_name='reactions_as_reactant', to='chemistry.element', verbose_name='Реагенты')),
            ],
            options={
                'verbose_name': 'Химическая реакция',
                'verbose_name_plural': 'Химические реакции',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='chemistry.elementcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ElementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melting_point', models.FloatField(blank=True, null=True, verbose_name='Температура плавления (°C)')),
                ('boiling_point', models.FloatField(blank=True, null=True, verbose_name='Температура кипения (°C)')),
                ('electron_configuration', models.CharField(blank=True, max_length=100, verbose_name='Электронная конфигурация')),
                ('electronegativity', models.FloatField(blank=True, null=True, verbose_name='Электроотрицательность')),
                ('discovery_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год открытия')),
                ('discovered_by', models.CharField(blank=True, max_length=255, verbose_name='Кем открыт')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='chemistry.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Детали элемента',
                'verbose_name_plural': 'Детали элементов',
            },
        ),
    ]
