# Generated by Django 5.1.6 on 2025-04-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='state',
            field=models.CharField(choices=[('solid', 'Твёрдое'), ('liquid', 'Жидкое'), ('gas', 'Газообразное')], default='solid', max_length=10, verbose_name='Агрегатное состояние'),
        ),
    ]
