# Generated by Django 5.1.6 on 2025-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_element_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('embed_code', models.TextField(help_text='Вставьте код <iframe> с VK Video', verbose_name='Код вставки (Embed code)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Используется для сортировки (меньше = выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='applications',
            field=models.TextField(blank=True, verbose_name='Применение'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='Плотность (г/см³)'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='discovery_info',
            field=models.TextField(blank=True, verbose_name='История открытия'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='electron_shell_image',
            field=models.ImageField(blank=True, null=True, upload_to='electron_shells/', verbose_name='Изображение электронных оболочек'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='fun_facts',
            field=models.TextField(blank=True, verbose_name='Интересные факты'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='thermal_conductivity',
            field=models.FloatField(blank=True, null=True, verbose_name='Теплопроводность (Вт/(м·К))'),
        ),
    ]
